### ISSUE TITLE
#VAL showing up in variable editor window

### ISSUE THREAD

**Issue by stillpointx** [flathub/org.octave.Octave#71] opened 2019-07-28 04:20 UTC
I'm using Octave 5.1.0 on Ubuntu 18.04 64bit

I'm getting **#VAL** for variables in the **Variable Editor Window.**  But if I type the variable in the **Command Line Window** the numbers the variable contain work.

Test code:
```
fs_rate=1000;
len_of_sig=1; %length of signal in seconds
t=linspace(0,len_of_sig,fs_rate*len_of_sig);
y=.3*sin(2*pi*2*t);
amp_to_find=.25;

x = diff(sign(y));
idx_up = find(x>amp_to_find);
idx_dwn = find(x<-amp_to_find);

idx_up_numel=ones(1,numel(idx_up));
idx_dwn_numel=ones(1,numel(idx_dwn));
```
![screenshot-July-28-2019-00:18:59](https://user-images.githubusercontent.com/28985314/62002210-5c9ba800-b0cd-11e9-9c92-3b2ea2563ff9.png)

![screenshot-July-28-2019-00:27:58](https://user-images.githubusercontent.com/28985314/62002268-97eaa680-b0ce-11e9-8d2f-f6a0c4604ad2.png)

**Comment by mtmiller** [comment] 2019-07-28 19:30
This is an upstream missing feature in Octave. I've gone ahead and reported this as [Octave#56690](https://savannah.gnu.org/bugs/?56690). There's nothing to do in the packaging except wait for a version of Octave with this feature implemented.

**Comment by stillpointx** [comment] 2019-07-28 19:50
Thanks for the update :-)

**Comment by Alexander-Wilms** [comment] 2021-08-08 19:42
Can still reproduce this, but since it's been reported upstream, I'm closing this issue.

**Closed by Alexander-Wilms** 2021-08-08 19:42 UTC
Labels: enhancement, good first issue, upstream
