### ISSUE TITLE
Octave documentation error

### ISSUE THREAD

**Issue by kupiqu** [flathub/org.octave.Octave#45] opened 2019-01-26 15:33 UTC
At Octave 5 startup I get the following pop-up error:

```
Could not copy help collection to temporary file. Search capabilities may be affected.
Cannot create index tables in file /app/share/octave/5.0.90/doc/octave_interpreter.qhc.
```

After I press Ok, Octave launches, but documentation is not available.

Not sure this is a problem of flatpak or Octave, checking this out here first.

**Comment by Alexander-Wilms** [comment] 2019-01-26 17:05
Can reproduce

**Comment by mtmiller** [comment] 2019-01-26 19:49
Same, can reproduce, seems to only be an error with Qt 5.12, not 5.11. If that is the bug, looks like it should be fixed in Qt 5.12.1.

**Comment by dmanea28** [comment] 2019-01-27 12:00
Same, can reproduce

**Comment by mtmiller** [comment] 2019-02-09 21:38
[KDE runtime](https://github.com/KDE/flatpak-kde-runtime/tree/qt5.12lts) has been updated to 5.12.1, just needs to be built and published.

**Comment by mtmiller** [comment] 2019-02-13 23:13
@Alexander-Wilms Is there somewhere to file bugs against the org.kde.Sdk runtime? I tried forcing the help files to be rebuilt, and the build failed with

    /bin/sh: line 3: 16634 Segmentation fault      qhelpgenerator doc/interpreter/octave_interpreter.qhcp -o doc/interpreter/octave_interpreter.qhc > /dev/null

Something is fatally wrong with the build of this program in the Sdk:

    $ flatpak run --devel --runtime=org.kde.Sdk --runtime-version=5.12 --command=bash org.octave.Octave
    $ moc -v
    moc 5.12.0
    $ uic -v
    uic 5.12.0
    $ qhelpgenerator -h
    Segmentation fault
    $ qhelpgenerator -v
    Segmentation fault

**Comment by kupiqu** [comment] 2019-02-13 23:17
I would recommend submitting a bug to kde, maybe this is the product to link it to:

https://bugs.kde.org/enter_bug.cgi?product=flatpak-platform-plugin

If not, kde devs will redirect...

**Comment by aleixpol** [comment] 2019-02-14 02:33
5.12.1 is getting a bit delayed because of some arm issues, hopefully to be fixed already (build takes a while).

I can reproduce the issue with
```
$ flatpak run --command=bash --devel org.kde.Sdk//5.12
$ qhelpgenerator --help
Segmentation fault (core dumped)
```

Let's see if it gets fixed by 5.12.1 and if it doesn't we'll have to dive into the issue.

**Comment by perebalazs** [comment] 2019-02-16 16:16
How can I install 5.12.1? At this moment 5.12 is the default,
flatpak install flathub org.kde.Sdk//5.12.1
doesn't work.

**Comment by aleixpol** [comment] 2019-02-17 13:00
There's some issues in flathub, they're trying to get it sorted out:
https://flathub.org/builds/#/builders/2/builds/8204

**Comment by perebalazs** [comment] 2019-02-21 15:07
I installed the new org.kde.Sdk (just now), but the original error is present yet. Howcan I revert to octave 4.4.1 which worked properly.

**Comment by mtmiller** [comment] 2019-02-21 18:49
This is fixed with 5.12.1 and Octave's stable branch, specifically [c66f509d9f5c](https://hg.savannah.gnu.org/hgweb/octave/rev/c66f509d9f5c). I've tested locally by applying that as a patch against 5.0.91 and by building a snapshot of the current stable branch, both work for me now with 5.12.1. We can close this by either cherry picking the patch or waiting for Octave 5.1, which should be released very soon, hopefully within the next week.

**Comment by mtmiller** [comment] 2019-02-21 18:55
@aleixpol I still get a segmentation fault with qhelpgenerator in 5.12.1, should I file a bug somewhere for that?

**Comment by perebalazs** [comment] 2019-02-24 10:41
Today morning a new build arrived via flathub, but with the same doc issue. :-(

**Comment by mtmiller** [comment] 2019-02-25 20:26
Closing, this should now be fixed with 5.1, updated in a9ff763a0301.

**Closed by mtmiller** 2019-02-25 20:26 UTC

**Comment by refi64** [comment] 2019-10-11 01:39
So I know this is a bit off-topic, but I'm encountering the qhelpgenerator segfault while building another Flatpak on the latest 5.12 and 5.13 SDKs. Was anyone here able to concretely work around / fix it?

**Comment by ghisvail** [comment] 2020-04-16 18:45
Same question as @refi64 

It would have been nice to provide a summary on how you folks went to the bottom of this issue for posterity.

**Comment by mtmiller** [comment] 2020-04-16 19:19
In summary, Octave ships the docs in the tarball, so the issue with qhelpgenerator was sidestepped, may have never been fixed for all I know.

**Comment by ghisvail** [comment] 2020-04-18 07:44
I see. I have just reported the issue upstream, here:

https://invent.kde.org/kde/flatpak-kde-runtime/-/issues/4
